geekshop/urls.py
"""geekshop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    # urlpatterns += [path('^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from .views import OrderDelete, OrderUpdate, OrderList, OrderDetail, \
    OrderCreate, order_forming_complete, basket_clear, get_product_price

app_name = 'ordersapp'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('basket_clear/', basket_clear, name='basket_clear'),
    path('product/<int:pk>/price/', get_product_price, name='product_price'),

    # path('payment/result/', payment_result, name='payment_result'),
]

users/urls.py
from django.urls import path

from .views import LoginListView, RegisterListView, Logout, ProfileFormView

app_name = 'users'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify'),
]

ordersapp/models.py
from django.db import models
from django.db.models.signals import pre_delete, pre_save
from django.dispatch import receiver

from baskets.models import Basket
from geekshop import settings
from products.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SEND_TO_PROCEED = 'STP'
    PAID = 'PD'
    PROCEEDED = 'PRD'
    READY = 'RDY'
    CANCEL = 'CNC'

    ORDER_STATUS_CHOICES = (
        (FORMING, 'формируется'),
        (SEND_TO_PROCEED, 'отправлено в обработку'),
        (PAID, 'оплачен'),
        (PROCEEDED, 'обрабатывается'),
        (READY, 'готовится к выдаче'),
        (CANCEL, 'отмена заказа'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(verbose_name='создан', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='обновлен', auto_now=True)
    status = models.CharField(choices=ORDER_STATUS_CHOICES, verbose_name='статус', max_length=3, default=FORMING)
    is_active = models.BooleanField(verbose_name='активный', default=True)

    def __str__(self):
        return f'Текущий заказ {self.pk}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.get_product_cost(), items)))

    def get_items(self):
        return self.orderitems.select_related()

    def delete(self, using=None, keep_parents=False):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.save()
        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, verbose_name='заказ', related_name='orderitems', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name='продукты', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk).quantity


@receiver(pre_delete, sender=Basket)
@receiver(pre_delete, sender=OrderItem)
def product_quantity_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


@receiver(pre_save, sender=Basket)
@receiver(pre_save, sender=OrderItem)
def product_quantity_update(sender, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - instance.get_item(int(instance.pk))
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()

ordersapp/forms.py
from django import forms

from ordersapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class OrderItemsForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Проверить, полезен или вреден
        # self.fields['product'].queryset = Product.objects.all().select_related()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

ordersapp/views.py
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from baskets.models import Basket
from geekshop.mixin import BaseClassContextMixin
from ordersapp.forms import OrderItemsForm
from ordersapp.models import Order, OrderItem
from products.models import Product


class OrderList(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user, is_active=True)


class OrderCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'GeekShop | Создать заказ'
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user)
            if basket_items:
                OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm,
                                                     extra=basket_items.count())
                formset = OrderFormSet()

                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price * basket_items[num].quantity

            else:
                formset = OrderFormSet()

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_cost() == 0:
                self.object.delete()

        return super().form_valid(form)


class OrderUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'GeekShop | Обновить заказ'
        OrderFormSet = inlineformset_factory(Order, OrderItem, form=OrderItemsForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            # Проверить потом, вот это улучшает или нет (или оно в методичке было)
            # queryset = self.object.orderitems.select_related()
            # formset = OrderFormSet(instance=self.object, queryset=queryset)
            formset = OrderFormSet(instance=self.object)
            for form in formset:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price * form.initial['quantity']

        context['orderitems'] = formset
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

            if self.object.get_total_cost() == 0:
                self.object.delete()

        return super().form_valid(form)


class OrderDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:list')


class OrderDetail(DetailView, BaseClassContextMixin):
    model = Order
    title = 'Geekshop | Просмотр заказа'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['headings'] = ['', 'Категория', 'Товар', 'Цена, руб/шт',
                               'Кол-во, шт', 'Общая сумма, руб', ]
        return context


def order_forming_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.SEND_TO_PROCEED
    order.save()
    if request.is_ajax():
        result = render_to_string('ordersapp/includes/inc_orders_table.html', request=request)
        return JsonResponse({'result': result})

    return HttpResponseRedirect(reverse('orders:list'))


def basket_clear(request):
    basket_items = Basket.objects.filter(user=request.user)
    basket_items.delete()

    if request.is_ajax():
        result = render_to_string('baskets/baskets.html')
        return JsonResponse({'result': result})
    return HttpResponseRedirect(reverse('users:profile'))


# Для приделывания робокассы:
# def payment_result(request):
#     status = request.GET.get('ik_inv_st')
#     if status == 'success':
#         order_pk = request.GET.get('ik_pm_no')
#         order_item = Order.objects.get(pk=order_pk)
#         order_item.status = Order.PAID
#         order_item.save()
#     return HttpResponseRedirect(reverse('orders:list'))

def get_product_price(request, pk):
    if request.is_ajax():
        product = Product.objects.get(pk=pk)
        if product:
            return JsonResponse({'price': product.price})

    return JsonResponse({'price': 0})

ordersapp/templates/ordersapp/includes/inc_order_actions.html
<div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;">
    {% if object.status == 'FM' %}
        <input class="btn btn-info form-control my-2 btn-lg" type="button"
               onclick="window.location.href = '{% url 'orders:forming_complete' object.pk %}';" value="Оформить">
        <input class="btn btn-info form-control my-2 btn-lg" type="button"
               onclick="window.location.href = '{% url 'orders:delete' object.pk %}';" value="Удалить">
    {% endif %}
    <input class="btn btn-info form-control my-2 btn-lg" type="button" onclick="window.location.href =
            {% url 'orders:list' %};" value="К списку заказов">
    <input class="btn btn-info form-control my-2 btn-lg" type="button" onclick="window.location.href =
            {% url 'products:index' %};" value="В каталог">
</div>

ordersapp/templates/ordersapp/includes/inc_order_summary.html
<div style="flex-grow: 5;">
    {% if object %}
        <div style=" color: darkcyan; background: #E0FFFF; padding: 20px" class="h3">Заказ №{{ object.pk }}
            от {{ object.created|date:"Y-m-d H:i:s" }}</div>
        <div style="padding: 20px">
            <div class="h5">Заказчик: <strong>{{ user.last_name }} {{ user.first_name }} </strong></div>
            <div class="h5">Обновлен: <strong>{{ object.updated|date:"Y-m-d H:i:s" }}</strong></div>
            <div class="h5">Статус: <strong>{{ object.get_status_display }}</strong></div>
        </div>
        <div style="background: #E0FFFF; padding: 20px">
            <div class="h5">
                Общее количество товаров: <strong><span class="order_total_quantity">
            {{ object.get_total_quantity }}</span></strong>
            </div>
            <div class="h5">
                Общая стоимость: <strong><span style="color: darkcyan; font-size: 22px" class="order_total_cost">
            {{ object.get_total_cost }}</span> руб </strong>
            </div>
        </div>

    {% else %}
        <div style="padding: 28px"></div>
        <div style=" color: darkcyan; background: #E0FFFF; padding: 20px" class="h3">Новый заказ</div>
        <div style="padding: 20px"><i style="color: darkcyan;" class="fa fa-exclamation-circle"></i> Обработка заказа
            может занимать до 3 рабочих дней в зависимости от загруженности склада
        </div>
        <div style="padding: 20px" class="h5">Заказчик: <strong>{{ user.last_name }} {{ user.first_name }}</strong>
        </div>
        {% if basket.0 %}
            <div style="background: #E0FFFF; padding: 20px">
                <div class="h5">
                    Общее количество товаров: <span class="order_total_quantity">
            {{ basket.0.get_total_quantity }}</span>
                </div>
                <div class="h4">
                    Общая стоимость: <span class="order_total_cost">
            {{ basket.0.get_total_cost }}</span> руб
                </div>
            </div>
        {% endif %}
    {% endif %}
</div>

ordersapp/templates/ordersapp/includes/inc_orders_table.html
<table class="table orders_list">
    <thead>
    <tr>
        <th>Сменить статус</th>
        <th>ID</th>
        <th>Создан</th>
        <th>Обновлен</th>
        <th>Статус</th>
        <th>Информация</th>
    </tr>
    </thead>
    <tbody>
    {% for item in orders %}
        {% if item.is_active %}
            <tr>
                <td>
                    {% if item.status == 'FM' %}
                        <div class="send_to_proceed">
                            <button type="button" id="to_proceed_btn" class="btn btn-primary" name="{{ item.id }}">
                                Оформить
                            </button>
                        </div>
                    {% elif item.status == 'CNC' %}
                        <p>Заказ отменен</p>
                    {% else %}
                        <p>Заказ в работе</p>
                    {% endif %}
                </td>
                <td class="td1 orders_list">{{ item.pk }}</td>
                <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                <td>{{ item.get_status_display }}</td>
                <td>
                    <a href="{% url 'orders:read' item.pk %}">
                        Посмотреть
                    </a>
                </td>
                <td>
                    {% if item.status == 'FM' %}
                        <a href="{% url 'orders:update' item.pk %}">
                            Редактировать
                        </a>
                    {% endif %}
                </td>
                <td>
                    {% if item.status == 'FM' %}
                        <a href="{% url 'orders:delete' item.pk %}">
                            Удалить
                        </a>
                    {% endif %}
                </td>
            </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>