admins/urls.py
from django.urls import path

from .views import index, UserListView, UserUpdateView, UserCreateView, UserDeleteView, \
    CategoriesListView, CategoriesUpdateView, CategoriesCreateView, CategoriesDeleteView, \
    ProductsListView, ProductsUpdateView, ProductsCreateView, ProductsDeleteView, user_is_staff

app_name = 'admins'
urlpatterns = [
    path('', index, name='index'),
    path('users/', UserListView.as_view(), name='admins_user'),
    path('users-create/', UserCreateView.as_view(), name='admins_user_create'),
    path('users-delete/<int:pk>/', UserDeleteView.as_view(), name='admins_user_delete'),
    path('users-update/<int:pk>/', UserUpdateView.as_view(), name='admins_user_update'),

    path('users-is-staff/<int:pk>/', user_is_staff, name='admins_user_is_staff'),

    path('categories/', CategoriesListView.as_view(), name='admins_categories'),
    path('categories/create/', CategoriesCreateView.as_view(), name='admins_category_create'),
    path('categories/update/<int:pk>/', CategoriesUpdateView.as_view(), name='admins_category_update'),
    path('categories/delete/<int:pk>/', CategoriesDeleteView.as_view(), name='admins_category_delete'),

    path('products/', ProductsListView.as_view(), name='admins_products'),
    path('products/update/<int:pk>/', ProductsUpdateView.as_view(), name='admins_product_update'),
    path('products/create/', ProductsCreateView.as_view(), name='admins_product_create'),
    path('products/delete/<int:pk>/', ProductsDeleteView.as_view(), name='admins_product_delete'),
]

geekshop/urls.py
"""geekshop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    # urlpatterns += [path('^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]

users/urls.py
from django.urls import path

from .views import LoginListView, RegisterListView, Logout, ProfileFormView

app_name = 'users'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify'),
]

admins/templates/admins/admin-categories-create.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>

            <div class="container-fluid">
                <form action="{% url 'admins:admins_category_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="mt-4">Создание категории</h1>
                    <div class="row">
                        <div class="col-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название кагегории</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.discount.id_for_label }}">Скидка</label>
                                {{ form.discount }}
                            </div>

                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание
                                    категории</label>
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="row">
                                <div class="col-lg-12" style="margin-top: 33px;">
                                    <input class="btn btn-info form-control my-2 btn-lg" type="submit"
                                           value="Сохранить">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12" style="margin-top: 33px;">
                                    <input type="button" class="btn btn-danger form-control my-2 btn-lg"
                                           onclick="window.location.href = '{% url 'admins:admins_categories' %}';"
                                           value="Отмена"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-categories-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории | {{ productcategory.name }}</h1>
                <form action="{% url 'admins:admins_category_update' productcategory.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-3">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.discount.id_for_label }}">Скидка</label>
                                {{ form.discount }}
                            </div>
                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="col-3">
                            <div class="row">
                                <div class="col-lg-12" style="margin-top: 33px;">
                                    <input class="btn btn-info form-control my-2 btn-lg" type="submit"
                                           value="Сохранить">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12" style="margin-top: 33px;">
                                    <input type="button" class="btn btn-danger form-control my-2 btn-lg"
                                           onclick="window.location.href = '{% url 'admins:admins_categories' %}';"
                                           value="Отмена"/>
                                </div>
                            </div>
                            {% if productcategory.available %}
                                <div class="row">
                                    <div class="col-lg-12" style="margin-top: 33px;">
                                        <form action="{% url 'admins:admins_category_delete' productcategory.id %}"
                                              method="post">
                                        </form>
                                        <form action="{% url 'admins:admins_category_delete' productcategory.id %}"
                                              method="post">
                                            {% csrf_token %}
                                            <input class="btn btn-secondary form-control my-2 btn-lg" value="Удалить"
                                                   type="submit">
                                        </form>
                                    </div>
                                </div>
                            {% else %}
                                <div class="row">
                                    <div class="col-lg-12" style="margin-top: 33px;">
                                        <form action="{% url 'admins:admins_category_delete' productcategory.id %}"
                                              method="post">
                                        </form>
                                        <form action="{% url 'admins:admins_category_delete' productcategory.id %}"
                                              method="post">
                                            {% csrf_token %}
                                            <input class="btn btn-success form-control my-2 btn-lg" value="Активировать"
                                                   type="submit">
                                        </form>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-products-create.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание продукта</h1>
                <form action="{% url 'admins:admins_product_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                            {{ form.price }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                            {{ form.quantity }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                        <div class="col-lg-3" style="margin-top: 33px;">
                            <input class="btn float-lg-right btn-info btn-block btn-lg" type="submit" value="Сохранить">
                        </div>
                        <div class="col-lg-3" style="margin-top: 33px;">
                            <input type="button" class="btn float-lg-right btn-danger btn-block btn-lg"
                                   onclick="window.location.href = '{% url 'admins:admins_products' %}';"
                                   value="Отмена"/>
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование продукта | {{ product.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_product_update' product.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                    {{ form.name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                    {{ form.category }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                                    {{ form.price }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                                    {{ form.quantity }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                            <div class="col-lg-6" style="padding-top: 25px">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение</label>
                                </div>
                                <input class="btn float-lg-right btn-info btn-block btn-lg" type="submit"
                                       value="Сохранить">
                                <input type="button" class="btn float-lg-right btn-danger btn-block btn-lg"
                                       onclick="window.location.href = '{% url 'admins:admins_products' %}';"
                                       value="Отмена"/>
                                {% if product.available %}
                                    <form action="{% url 'admins:admins_product_delete' product.id %}"
                                          method="post">
                                    </form>
                                    <form action="{% url 'admins:admins_product_delete' product.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-secondary form-control my-2 btn-lg" value="Удалить"
                                               type="submit">
                                    </form>
                                {% else %}
                                    <form action="{% url 'admins:admins_product_delete' product.id %}"
                                          method="post">
                                    </form>
                                    <form action="{% url 'admins:admins_product_delete' product.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-success form-control my-2 btn-lg" value="Активировать"
                                               type="submit">
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admins_user_update' user.id %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                    {{ form.last_name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row mb-2">
                            <div class="col-lg-12">
                                <div class="custom-file">
                                    {{ form.image }}
                                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                        изображение</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя
                                    пользователя</label>
                                {{ form.username }}
                            </div>
                            <div class="col-lg-6">
                                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                    почты</label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-4" style="margin-top: 33px;">
                                <input type="button" class="btn btn-danger btn-block"
                                       onclick="window.location.href = '{% url 'admins:admins_user' %}';"
                                       value="Отмена"/>
                            </div>
                            <div class="col-lg-4" style="margin-top: 33px;">
                                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                            </div>
                            <div class="col-lg-4" style="margin-top: 33px;">
                                {% if user.is_active %}
                                    <form action="{% url 'admins:admins_user_delete' user.id %}"
                                          method="post">
                                    </form>
                                    <form action="{% url 'admins:admins_user_delete' user.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-secondary btn-block"
                                               value="Удалить"
                                               type="submit">
                                    </form>
                                    </div>
                                {% else %}
                                    <form action="{% url 'admins:admins_user_delete' user.id %}"
                                          method="post">
                                    </form>
                                    <form action="{% url 'admins:admins_user_delete' user.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-success btn-block"
                                               value="Активировать"
                                               type="submit">
                                    </form>
                                {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/admin.html
{% extends 'admins/base.html' %}
{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Административная панель</h1>
                <div class="container" style="
                font-size: 500%;
                display: grid;
                grid-gap: 5px;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                grid-template-rows: repeat(2, 250px);">
                    <form action="{% url 'admins:admins_user' %}">
                        <button style="margin-top: 33px;width: 100%;
                        height: 100%;
                        object-fit: cover;" type="submit"><i class="fa fa-users"></i></button>
                    </form>
                    <form action="{% url 'admins:admins_categories' %}">
                        <button style="margin-top: 33px;width: 100%;
                        height: 100%;
                        object-fit: cover;" type="submit"><i class="fa fa-archive"></i></button>
                    </form>
                    <form action="{% url 'admins:admins_products' %}">
                        <button style="margin-top: 33px;width: 100%;
                        height: 100%;
                        object-fit: cover;" type="submit"><i class="fas fa-tshirt"></i></button>
                    </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

admins/templates/admins/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title|title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admins_user' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admins:admins_products' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                    <input type="button" class="btn btn-info btn-block"
                           onclick="window.location.href = '{% url 'products:index' %}';"
                           value="В каталог"/>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</div>
{#<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>#}
{#<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>#}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
{#<script src="{% static 'js/datatable.js'%}"></script>#}


<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/admins.js' %}"></script>
</body>
</html>