geekshop/urls.py
"""geekshop URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('orders/', include('ordersapp.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    # urlpatterns += [path('^__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r'^__debug_/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

from .views import OrderDelete, OrderUpdate, OrderList, OrderDetail, \
    OrderCreate, order_forming_complete, basket_clear, get_product_price

app_name = 'ordersapp'
urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('read/<int:pk>/', OrderDetail.as_view(), name='read'),
    path('forming_complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('basket_clear/', basket_clear, name='basket_clear'),
    path('product/<int:pk>/price/', get_product_price, name='product_price'),

    # path('payment/result/', payment_result, name='payment_result'),
]

products/urls.py
from django.urls import path

from .views import ProductsView, ModalWindow, ProductDetail

app_name = 'products'
urlpatterns = [
    path('', ProductsView.as_view(), name='index'),
    path('category/<int:category_id>/', ProductsView.as_view(), name='category'),
    path('page/<int:page_id>/', ProductsView.as_view(), name='page'),
    path('detail/<int:pk>/', ProductDetail.as_view(), name='detail'),
    path('modal/<int:pk>/', ModalWindow.as_view(), name='modal'),
]

users/urls.py
from django.urls import path

from .views import LoginListView, RegisterListView, Logout, ProfileFormView

app_name = 'users'
urlpatterns = [
    path('login/', LoginListView.as_view(), name='login'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
    path('logout/', Logout.as_view(), name='logout'),
    path('verify/<str:email>/<str:activation_key>/', RegisterListView.verify, name='verify'),
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    discount = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    available = models.BooleanField(default=True, db_index=True)

    # available = models.BooleanField(default=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'{self.name} | {self.category}'

products/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import ListView, DetailView

from .models import Product, ProductCategory


def index(request):
    context = {
        'title': 'Geekshop',
    }
    return render(request, 'products/index.html', context)


# def get_link_category():
# if settings.LOW_CACHE:
#     key = 'link_category'
#     link_category = cache.get(key)
#     if link_category is None:
#         link_category = ProductCategory.objects.all()
#         cache.set(key, link_category)
#     return link_category
# else:
#     return ProductCategory.objects.all()

# def get_link_product():
#     if settings.LOW_CACHE:
#         key = 'link_product'
#         link_product = cache.get(key)
#         if link_product is None:
#             link_product = Product.objects.all().select_related()
#             cache.set(key, link_product)
#         return link_product
#     else:
#         return Product.objects.all().select_related()

def get_product(pk):
    # if settings.LOW_CACHE:
    #     key = f'product{pk}'
    #     product = cache.get(key)
    #     if product is None:
    #         product = get_object_or_404(Product,pk=pk)
    #         cache.set(key, product)
    #     return product
    # else:
    #     return get_object_or_404(Product,pk=pk)
    return get_object_or_404(Product, pk=pk)


class ProductsView(ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Каталог'
        return context

        # def get_queryset(self):
        #     if self.kwargs.keys():
        #         return Product.objects.filter(category_id=self.kwargs['category_id'])
        #     return Product.objects.all()

        # Потом раскомментить эту строку!
        # return Product.objects.filter(category_id=self.kwargs['category_id']).select_related('category')
        #     products = get_link_product()
        #     return products
        # # return Product.objects.all()
        # return Product.objects.all().select_related('category')


class ModalWindow(ListView):
    model = Product
    template_name = 'products/modal.html'

    def get(self, request, *args, **kwargs):
        product_id = kwargs.pop('pk', None)
        context = {}
        if request.is_ajax():
            m_product = Product.objects.get(id=product_id)
            context['m_product'] = m_product
            result = render_to_string('products/modal.html', context, request=request)

            return JsonResponse({'result': result})
        return redirect(self)


class ProductDetail(DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, category_id=None, *args, **kwargs):
        context = super().get_context_data()
        context['product'] = get_product(self.kwargs.get('pk'))
        context['categories'] = ProductCategory.objects.all()
        return context


def paginate_me(queryset, num):
    paginator = Paginator(queryset, per_page=3)
    try:
        products_paginator = paginator.page(num)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    return products_paginator

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <style>
        select {
            font: inherit;
            letter-spacing: inherit;
            word-spacing: inherit;
            -moz-appearance: none;
            -webkit-appearance: none;
            appearance: none;
        }

        select:not([multiple]) {
            padding-right: 1.2em;
            background-repeat: no-repeat;
            background-position: calc(100% - 0.25em) 0.35em;
            background-size: 0.85em auto;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 80 80'%3E%3Cpath d='M70.3 13.8L40 66.3 9.7 13.8z' fill='%23000'%3E%3C/path%3E%3C/svg%3E");
        }

        select::-ms-expand {
            display: none;
        }

        tr:nth-child(even) {
            background-color: #E0FFFF;
        }
    </style>
</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                                <i class="fas fa-user-circle"></i> {{ user.username|default:'Пользователь' }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'users:profile' %}">
                                        Профиль
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'orders:list' %}">
                                        Заказы
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admins:index' %}">
                                <i class="fas fa-users-cog"></i> Админка
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i
                                class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/baskets.js' %}"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>
</body>

</html>

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}


{% block css %}
    <link href="{% static  'css/index.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

products/templates/products/modal.html
{% load method %}
<form class="modal fade" id="productModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
    {% csrf_token %}
    <div class="product_viewer">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <h5 style="padding-top: 15px; font-size: 24px; font-style: oblique; text-decoration: underline;
                color: darkcyan;" class="modal-title" id="exampleModalLabel">{{ m_product.name }}</h5>
                <div class="modal-header">
                    <div class="card-body">
                        {% if user.is_authenticated %}
                            <div>
                                <p class="card-text">Обычная цена</p>
                                <h4><s>{% discount m_product.price %}</s> руб.</h4>
                                <p class="card-text">Цена с накопительной скидкой</p>
                                <h4><s>{{ m_product.price }}</s> руб.</h4>
                            </div>
                            <div style="background-color:#AFEEEE; padding: 10px;">
                                <p class="card-text">Специальная цена для вас, <strong>{{ user.username }}</strong>,
                                    только <strong>{% now 'j E' %}</strong></p>
                                <h2><strong>{% real_discount m_product %}</strong> руб.</h2>
                            </div>
                            <h6>Этот товар сейчас просматривают <span id="random"></span> человек </h6>
                        {% else %}
                            <div>
                                <p class="card-text">Обычная цена</p>
                                <h4><s>{% discount m_product.price %}</s> руб.</h4>
                            </div>
                            <div style="background-color:#AFEEEE; padding: 10px;">
                                <p class="card-text">Специальная цена в рамках акции, только
                                    <strong>{% now 'j E' %}</strong></p>
                                <h2><strong>{% real_discount m_product %}</strong> руб.</h2>
                                <p class="card-text">Успейте <a href="{% url 'users:register' %}">
                                    зарегистрироваться</a> или <a href="{% url 'users:login' %}">
                                    войдите в личный кабинет</a></p>
                            </div>
                            <h6>Этот товар сейчас просматривают <span id="random"></span> человек </h6>
                        {% endif %}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
</form>

products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static '/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <form action="{% url 'products:index' %}">
                        <button style="width: 100%;" type="submit" class="btn btn-outline-info btn-lg my-2">
                            <i class="fa fa-shopping-bag"></i> В каталог
                        </button>
                    </form>
                    <button onClick="javascript:history.go(-1);" type="submit" class="btn btn-outline-info btn-lg my-2">
                        <i class="fa fa-undo"></i> Назад
                    </button>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="row my-5">
                    <div class="card" style="width: 100%; font-size: 20px; text-align: justify;">
                        <div class="container" style="display: flex;">
                            <div style="width: 80%;" class="item">
                                <img src="/media/{{ product.image }}" class="card-img-top" alt="...">
                            </div>
                            <div class="item">
                                <div class="card-body">
                                    <strong><p style="font-size: 24px;text-align:center;" class="card-title">
                                        {{ product.name }}</p></strong>
                                    <hr>
                                    <p class="card-text" style="text-indent: 30px;">{{ product.description }}</p>
                                    <hr>
                                    <p class="card-text"
                                       style="color:darkcyan; text-indent: 20px; font-size: 18px;">{{ product.category.description }}</p>
                                </div>
                                <ul class="list-group list-group-flush" style="text-align:right;">
                                    <li class="list-group-item">{{ product.price }} руб</li>
                                    <li class="list-group-item">В наличии: {{ product.quantity }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">GeekShop</h1>
                <div class="list-group" style="font-size: 22px">
                    {% for category in categories %}
                        {% if category.available %}
                            <a href="{% url 'products:category' category.id %}"
                               class="list-group-item">{{ category }}</a>
                        {% endif %}
                    {% endfor %}
                    <input class="btn btn-info form-control my-2 btn-lg" type="button"
                           onclick="window.location.href = '{% url 'products:index' %}';" value="Все товары">
                    <input class="btn btn-info form-control my-2 btn-lg" type="button"
                           onclick="window.location.href = '{% url 'users:profile' %}';" value="Ваш профиль">
                    {% if user.is_authenticated %}
                        <input class="btn btn-info form-control my-2 btn-lg" type="button"
                               onclick="window.location.href = '{% url 'orders:list' %}';" value="Ваши заказы">
                    {% endif %}
                </div>
            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
                <div class="modal_catcher" style="text-align: center">
                    {% include "products/modal.html" %}
                    <div class="product_catcher">
                        {% include 'include/product_items.html' %}
                    </div>
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not product_set.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if product_set.has_previous %} ?page={{ product_set.previous_page_number }}
                               {% else %} # {% endif %}"
                               tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% for page in product_set.paginator.page_range %}
                            <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}
                        <li class="page-item {% if not product_set.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if product_set.has_next %} ?page={{ product_set.next_page_number }} {% else %} # {% endif %}">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

{% block footer %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}